# Generated by Django 4.1.4 on 2022-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custombrandsettings',
            options={'verbose_name': 'Custom branding'},
        ),
        migrations.AlterField(
            model_name='custombrandsettings',
            name='login_message',
            field=models.CharField(blank=True, help_text='Your Login message', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='custombrandsettings',
            name='welcome_message',
            field=models.CharField(blank=True, help_text='Your Welcome message', max_length=30, null=True),
        ),
    ]
