# Generated by Django 4.1.4 on 2022-12-14 15:04

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategory_blogpage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('html', wagtail.blocks.RawHTMLBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('video', wagtail.embeds.blocks.EmbedBlock())], icon='cogs'))], use_json_field=True),
        ),
    ]
