# Generated by Django 4.1.4 on 2022-12-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_socialmedianameurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmediasettings',
            options={'verbose_name': 'social media'},
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
    ]
